#relational operators
print('enter the values')
a=int(input())
b=int(input())
print('graterthan:',a>b)
print('lessthan:',a<b)
print('graterthan or equalto:',a>=b)
print('lessthan or equalto:',a<=b)
print('equals to:',a==b)
print('not equals to:',a!=b)
